### ISSUE TITLE
Update for 0.17

### ISSUE THREAD

**Issue by cgarciae** [chendrix/elm-matrix#3]

**Comment by chendrix** [comment]
Hi there @cgarciae! Thanks for opening this issue! 

Unfortunately I'm going on vacation for the next few weeks and won't have access to a computer for development. I will make sure to get to this as soon as possible!

**Comment by chendrix** [comment]
@cgarciae This has been updated for elm 0.17 as of c63819a (version 3.1.1)

Thanks again for raising this issue :bowtie:
